# Generated by Django 4.2.1 on 2024-12-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_db',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
