# Generated by Django 4.2.1 on 2024-12-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_data_db_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_db',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
