# Generated by Django 4.2.1 on 2025-01-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_alter_data_db_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_db',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=1),
        ),
    ]
